"""Dashboard: displays the outputs already generated by `make pipeline`.

Run with: streamlit run streamlit_app.py  (or `make dashboard`)
Run `make pipeline` first if output/ is empty or stale.
"""
from pathlib import Path

import pandas as pd
import streamlit as st

ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "output"

st.set_page_config(page_title="Miraclib Cell Population Dashboard", layout="wide")
st.title("Miraclib Immune Cell Population Dashboard")

if not OUTPUT.exists() or not any(OUTPUT.iterdir()):
    st.error("No files in output/. Run `make pipeline` first.")
    st.stop()

st.header("Part 2 — Population frequencies per sample")
freq_csv = OUTPUT / "population_frequencies.csv"
if freq_csv.exists():
    st.dataframe(pd.read_csv(freq_csv), use_container_width=True, hide_index=True)
else:
    st.warning("output/population_frequencies.csv not found. Run `python part2.py`.")

st.header("Part 3 — Responders vs. non-responders")
boxplot_png = OUTPUT / "part3_boxplots.png"
if boxplot_png.exists():
    st.image(str(boxplot_png))
else:
    st.warning("output/part3_boxplots.png not found. Run `python part3.py`.")

significance_md = OUTPUT / "part3_significance.md"
if significance_md.exists():
    st.markdown(significance_md.read_text())
else:
    st.warning("output/part3_significance.md not found. Run `python part3.py`.")

st.header("Part 4 — Baseline (day 0) subset")
baseline_csv = OUTPUT / "part4_baseline_samples.csv"
if baseline_csv.exists():
    st.dataframe(pd.read_csv(baseline_csv), use_container_width=True, hide_index=True)
else:
    st.warning("output/part4_baseline_samples.csv not found. Run `python part4.py`.")

extensions_csv = OUTPUT / "part4_extensions.csv"
if extensions_csv.exists():
    st.dataframe(pd.read_csv(extensions_csv), use_container_width=True, hide_index=True)
else:
    st.warning("output/part4_extensions.csv not found. Run `python part4.py`.")
